"""Create initial tables

Revision ID: aa84cfd30b1c
Revises: 
Create Date: 2025-06-08 19:05:54.845938+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa84cfd30b1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('document_hash', sa.String(), nullable=False),
    sa.Column('obligated_party', sa.String(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.String(), nullable=True),
    sa.Column('clause_text', sa.Text(), nullable=True),
    sa.Column('clause_number', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_document_hash'), 'obligations', ['document_hash'], unique=False)
    op.create_index(op.f('ix_obligations_id'), 'obligations', ['id'], unique=False)
    op.create_table('obligation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(), nullable=False),
    sa.Column('issue_url', sa.String(), nullable=True),
    sa.Column('tool_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CREATED', 'FAILED', 'UPDATED', name='issuestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('issue_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligation_issues_id'), 'obligation_issues', ['id'], unique=False)
    op.create_index(op.f('ix_obligation_issues_issue_key'), 'obligation_issues', ['issue_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligation_issues_issue_key'), table_name='obligation_issues')
    op.drop_index(op.f('ix_obligation_issues_id'), table_name='obligation_issues')
    op.drop_table('obligation_issues')
    op.drop_index(op.f('ix_obligations_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_document_hash'), table_name='obligations')
    op.drop_table('obligations')
    # ### end Alembic commands ###
